### ISSUE TITLE
plugin breaks with facebook ios sdk 3.17.1

### ISSUE THREAD

**Issue by mlevkovsky** [ccsoft/cordova-facebook#39]
When I try to build with the facebook ios sdk version 3.17.1 I get this error:

/Users/mlevkovsky/Desktop/airborne/app/trunk/platforms/ios/FacebookSDK.framework/Headers/FBShareDialogParams.h:27:12: note: 
      'FBShareDialogParams' declared here
@interface FBShareDialogParams : FBLinkShareParams
           ^
/Users/mlevkovsky/Desktop/airborne/app/trunk/platforms/ios/Airborne/Plugins/com.ccsoft.plugin.CordovaFacebook/CordovaFacebook.m:321:24: error: 
      no setter method 'setDescription:' for assignment to property
    params.description = [command.arguments objectAtIndex:4];
    ~~~~~~~~~~~~~~~~~~ ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2 warnings and 1 error generated.

*\* BUILD FAILED **

Everything works fine with ios sdk 3.16.1 though. Any thoughts?
